import os
import re
import shutil
from pathlib import Path

from fontTools.ttLib import TTFont


ROOTS = [
    Path("D:\\\u5b57\u4f53\u5305\\\u82f1\u6587\u5b57\u4f53BR"),
    Path("D:\\\u5b57\u4f53\u5305\\MiSans\\otf"),
    Path("D:\\\u5b57\u4f53\u5305\\\u65b9\u6b63\u5170\u4ead-\u54c1\u724c\u8d44\u6e90\\\u65b9\u6b63\u5170\u4ead"),
    Path("D:\\\u5b57\u4f53\u5305\\M_PLUS_1p"),
    Path("D:\\\u5b57\u4f53\u5305\\Source Han Serif (2)\\Source Han Serif"),
    Path("D:\\\u5b57\u4f53\u5305\\\u6c49\u4eea\u96c5\u9177\u9ed1"),
]

PROJECT = Path(__file__).resolve().parents[1]
CSS_FILE = PROJECT / "apps" / "web" / "src" / "app" / "fonts.css"
REGISTRY_FILE = PROJECT / "apps" / "web" / "src" / "lib" / "font-registry.generated.ts"
ASSET_DIR = PROJECT / "apps" / "web" / "assets" / "fonts"

CSS_FAMILY_ALIASES = {
    "Source Han Serif": ["Source Han Serif", "Source Han Serif SC", "Source Han Serif TC"],
}


def font_name(font: TTFont, name_ids: list[int]) -> str | None:
    for name_id in name_ids:
        for record in font["name"].names:
            if record.nameID == name_id:
                try:
                    return record.toUnicode()
                except Exception:
                    continue
    return None


def css_weight(style: str, os_weight: int) -> int:
    normalized = style.lower().replace(" ", "")
    weights = {
        "thin": 100,
        "extralight": 200,
        "light": 300,
        "normal": 400,
        "regular": 400,
        "medium": 500,
        "demibold": 600,
        "semibold": 600,
        "bold": 700,
        "extrabold": 800,
        "heavy": 900,
        "black": 900,
    }
    normalized = normalized.replace("italic", "")
    return weights.get(normalized, os_weight)


faces: list[dict[str, str | int]] = []

missing_roots = [str(root) for root in ROOTS if not root.exists()]
if missing_roots:
    raise FileNotFoundError(f"Missing font roots: {', '.join(missing_roots)}")

ASSET_DIR.mkdir(parents=True, exist_ok=True)

for root in ROOTS:
    sources = {source.resolve() for source in [*root.rglob("*.otf"), *root.rglob("*.ttf"), *root.rglob("*.TTF")]}
    for source in sorted(sources):
        font = TTFont(source)
        family = font_name(font, [16, 1]) or source.stem
        style = font_name(font, [17, 2]) or "Regular"
        postscript = font_name(font, [6]) or source.stem
        weight = css_weight(style, getattr(font["OS/2"], "usWeightClass", 400))
        font_style = "italic" if "italic" in style.lower() else "normal"
        slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", postscript).strip("-").lower()
        asset_name = f"{slug}{source.suffix.lower()}"
        asset_path = ASSET_DIR / asset_name
        font.close()
        if not asset_path.exists() or asset_path.stat().st_size != source.stat().st_size:
            shutil.copy2(source, asset_path)
        faces.append(
            {
                "id": slug,
                "file": asset_name,
                "family": family,
                "weight": weight,
                "style": font_style,
                "format": "opentype" if source.suffix.lower() == ".otf" else "truetype",
            }
        )

if not faces:
    raise RuntimeError("No font files were found; generated files were left untouched.")

lines = ["/* Generated by scripts/build_web_fonts.py. */"]
for face in faces:
    for css_family in CSS_FAMILY_ALIASES.get(str(face["family"]), [str(face["family"])]):
        lines.extend(
            [
                "@font-face {",
                f'  font-family: "{css_family}";',
                f'  src: url("/api/fonts/{face["id"]}") format("{face["format"]}");',
                f'  font-weight: {face["weight"]};',
                f'  font-style: {face["style"]};',
                "  font-display: block;",
                "}",
                "",
            ]
        )

CSS_FILE.write_text("\n".join(lines), encoding="utf-8")
registry = [
    "/* Generated by scripts/build_web_fonts.py. */",
    "export const FONT_FILES = " + repr({face["id"]: face for face in faces}) + " as const;",
]
REGISTRY_FILE.write_text("\n".join(registry) + "\n", encoding="utf-8")
print(f"Registered {len(faces)} font faces")
